CREATE TABLE users (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE patients (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "pesel" varchar,
  "phone" varchar
);

CREATE TABLE doctors (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "specialization" varchar,
  "license_number" varchar
);

CREATE TABLE doctor_availability (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "is_available" boolean DEFAULT true
);

CREATE TABLE appointments (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int NOT NULL,
  "doctor_id" int NOT NULL,
  "availability_id" int,
  "appointment_date" timestamp NOT NULL,
  "status" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE prescriptions (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doctor_id" int NOT NULL,
  "patient_id" int NOT NULL,
  "appointment_id" int,
  "issued_at" timestamp,
  "notes" text
);

CREATE TABLE prescription_items (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prescription_id" int NOT NULL,
  "medication_name" varchar NOT NULL,
  "dosage" varchar,
  "instructions" text
);

CREATE TABLE notifications (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "type" varchar NOT NULL,
  "title" varchar,
  "content" text,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp
);